### ISSUE TITLE
Combine DAI transfers in mint()

### ISSUE THREAD

**Issue by slgraham** [save-dai/savedai-contract-v1#24]
Scott will be sending us code to accurately calculate cDAI amount minted, which will make this possible.

Will also allow us to use `saveDaiPriceInDaiCurrent` in `mint`

**Comment by kseniya292** [comment]
**From Scott:** 

Here is the code i mentioned related to rounding.

https://github.com/Keydonix/dai-hrd/blob/master/contracts/DaiHrd.sol#L572

This is from a project I worked on for tokenizing the DSR, and needing to join/exit based on the value of the DSR, which was constantly going up; very similar to cDAI.

It sould be something like this:

```
function _getCostofAsset(uint256 _amount) internal returns (uint256) {
        // calculate DAI needed to mint _amount of cDAI
        uint256 exchangeRate = cDai.exchangeRateCurrent();
        emit ExchangeRate(exchangeRate);
        // return _amount.mul(exchangeRate).div(10**18);
        return _amount.mul(exchangeRate).add(10**18-1).div(10**18);
    }
```
Adding one less than the number you are dividing by ensures that, if it is an exact multiple of 10**18, it will round that addition right back down. any other non-divisible-by-10**18, it will get rounded down from the next number up.

**Comment by dougiebuckets** [comment]
@kseniya292 You want to update `mint` to return a `boolean` when addressing this ticket?

**Comment by kseniya292** [comment]
@dougiebuckets Yes. I can do all the tickets involving the `mint` function.
