### ISSUE TITLE
Set public addresses as constants

### ISSUE THREAD

**Issue by slgraham** [save-dai/savedai-contract-v1#25]

**Comment by dougiebuckets** [comment]
@kseniya292, @slgraham - We can close this now that we're passing in addresses to the constructor.

**Comment by slgraham** [comment]
@dougiebuckets @kseniya292 what's the reason to pass the addresses into the constructor? 

I'm concerned that would prevent others from reading those values from the contract.

**Comment by kseniya292** [comment]
@slgraham when we deploy to Kovan and Rinkbey, we need to use the contract addresses for the testnets. Setting them in the constructor allows us to dynamically pass in the contract addresses we need to use based on where it's being deployed. 
We are setting the addresses for the interfaces which are all public, so you can access them:
```    
UniswapFactoryInterface public uniswapFactory;
UniswapExchangeInterface public daiUniswapExchange;
UniswapExchangeInterface public ocDaiExchange;
CTokenInterface public cDai;
OTokenInterface public ocDai;
 IERC20 public dai;
```
You can test by adding a test:
``` 
it('gets addresses', async () => {
    const address = await savedaiInstance.uniswapFactory();
    console.log(address)
  });
```
address returns the mainnet uniswapFactory address when running the forked mainnet ganache blockchain

**Comment by kseniya292** [comment]
@slgraham Also, we will add them to the docs, similar to Opyn: https://opyn.gitbook.io/opyn/abis-smart-contract-addresses
